version: "3.8"

services:
  sistema_gestao_app:
    build: .
    container_name: sistema_gestao_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal  # Acesso ao PostgreSQL do Windows Server
      DB_PORT: 5432
      DB_NAME: sistema_gestao
      DB_USER: postgres
      DB_PASSWORD: admin
      JWT_SECRET: "${JWT_SECRET}"

      

volumes:
  postgres_data:
