spring:
  application:
    name: sistema-gestao

  # Definindo explicitamente o perfil ativo como não sendo dev
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  # Configuração do banco de dados
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Configuração para resolver dependência circular
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /sistema-gestao
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 horas em milissegundos

logging:
  level:
    org.springframework.security: INFO
    com.oficina: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
