spring:
  application:
    name: sistema-gestao

server:
  port: 8080
  servlet:
    context-path: /sistema-gestao

#  datasource:
#    url: jdbc:postgresql://localhost:5432/sistema_gestao
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#    dialect: org.hibernate.dialect.PostgreSQLDialect
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  # Configuração para inicializar o schema antes de executar data.sql
    jpa:
     defer-datasource-initialization: true
    sql:
      init:
        mode: always
        continue-on-error: false

  datasource:
    url: jdbc:h2:file:./data/oficina
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: MINHA_CHAVE_SECRETA_123456789
    expiration: 86400000  # Tempo de expiração do token (em milissegundos) - 1 dia
    refresh-token:
      expiration: 604800000  # Tempo de expiração do refresh token (7 dias)

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: INFO
    security: DEBUG


#security:
#    user:
#      name: sa
#      password: password
