spring:
  application:
    name: sistema-gestao

  # Definindo explicitamente o perfil ativo como não sendo dev
  profiles:
    active: default

  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_gestao
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Configuração para resolver dependência circular
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /sistema-gestao
  port: 8080

jwt:
  secret: ${JWT_SECRET:chave-secreta-temporaria-deve-ser-substituida-em-producao}
  expiration: 86400000 # 24 horas em milissegundos

logging:
  level:
    org.springframework.security: INFO
    com.oficina: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
