spring:
  datasource:
    # use o POOLER IPv4 do Supabase (transaction) com ssl
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 15000
      max-lifetime: 600000
      data-source-properties:
        preferQueryMode: simple

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  # Render define ${PORT}; mantemos fallback 8080
  port: ${PORT:8080}
  servlet:
    context-path: /sistema-gestao

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.security: INFO
    com.oficina: INFO
