spring:
  application:
    name: sistema-gestao

  # Configuração do banco de dados H2
  datasource:
    url: jdbc:h2:file:./data/oficina
    driverClassName: org.h2.Driver
    username: sa
    password: password

  # Configuração do console H2
  h2:
    console:
      enabled: true
      path: /h2-console

  # Configuração JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  # Configuração de inicialização SQL
  sql:
    init:
      mode: always
      platform: h2
      continue-on-error: false

  # Configuração JWT
  jwt:
    secret: MINHA_CHAVE_SECRETA_123456789
    expiration: 86400000  # Tempo de expiração do token (em milissegundos) - 1 dia
    refresh-token:
      expiration: 604800000  # Tempo de expiração do refresh token (7 dias)

  # IMPORTANTE: Adicionar esta configuração para resolver o problema de dependência circular
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

# Configuração do servidor
server:
  port: 8080
  servlet:
    context-path: /sistema-gestao

# Configuração de logging
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG

