spring:
  application:
    name: sistema-gestao

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&preferQueryMode=simple
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 15000
      max-lifetime: 600000
      data-source-properties:
        preferQueryMode: simple

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /sistema-gestao

management:
  server:
    # usa a MESMA porta do app (a do Render: $PORT)
    port: ${PORT:8080}
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true       # habilita /actuator/health/liveness e /readiness
      show-details: never
  health:
    # Se o health continuar atrasando por causa do DB, troque para "false" temporariamente:
    db:
      enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.oficina: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
